### ISSUE TITLE
Input that causes a deindentation is not synced

### ISSUE THREAD

**Issue by libre-man** [yjs/y-codemirror#11]
**Checklist**

* [X] Are you reporting a bug? Use github issues for bug reports and feature requests. For general questions, please use https://discuss.yjs.dev/
* [X] Try to report your issue in the correct repository. Yjs consists of many modules. When in doubt, report it to https://github.com/yjs/yjs/issues/

**Describe the bug**
Closing brackets that cause deindentation are not synced correctly in the demo.

**To Reproduce**
1. Go to the [demo](https://demos.yjs.dev/codemirror/codemirror.html) with two different browsers
2. In one browser type
```
function a() {
 return 5;
```
3. Verify that the code is visible in the other browser
4. Now type in `}` (which should cause the editor to jump back to column 0 and insert `}` there).
5. Verify that the `}` is **not** visible in the other browser.

**Expected behavior**
All input should be the same across browsers.

**Environment Information**
 - Enviroment: Firefox (81) and Chromium
 - Yjs version and the versions of the y-* modules you are using: No idea, whatever is running on the demo site.

**Comment by anjalikk14** [comment]
I think it's anything with a deindent -- I was using codemirror with yjs bindings on html and deindented html tags would behave weirdly

**Comment by anjalikk14** [comment]
I put a debugger in the code mirror textType binding to see what was happening with incoming events. It looks like the 'retain' event is off by one when there's a deindent coming in from code mirror. This causes the subsequent events to be out of sync.

**Comment by dmonad** [comment]
Thanks for reporting this @libre-man & thanks for checking the issues @anjalikk14.

The CodeMirror change events are hard to interpret correctly. The change events happen on the old document state and result in a new document state. But at the time the event is fired, only the new state is accessible. From the new state, it is not possible to calculate the correct index position correctly when multiple changes happen in a single operation. This is not a bug in CodeMirror.

I changed it so that when multiple changes are fired we calculate diff and apply that on the Yjs type. This is pretty performant and good enough for now. I hope that we can do better in CodeMirror 6.

This is fixed in y-codemirror@2.0.9.

**Comment by anjalikk14** [comment]
Looks like this fixed it for the html I was working on. Thanks so much!
